### ISSUE TITLE
myIpAddress hangs for >30s if connect to 8.8.8.8 is silently dropped

### ISSUE THREAD

**Issue by rosesandhello** [TooTallNate/node-pac-resolver#18]
So, in the case that a firewall chooses to silently drop packets to 8.8.8.8, the myIpAddress function hangs for an unacceptable amount of time.

Proposed workaround is something like:

`  socket.setTimeout(500);
  socket.once('timeout', function(err) {
    fn(null, ip.address());
  });`

**Comment by TooTallNate** [comment]
👍 Patch welcome

**Comment by rosesandhello** [comment]
Done: #19

**Comment by steffenrumpf** [comment]
Sadly not merged until now... I've the same issue...

**Comment by Morl99** [comment]
It looks like this issue is still unresolved, we are struggling with this and it makes node-pac-resolver unusable for us. @TooTallNate what would be needed to get the Patch merged?

**Comment by Morl99** [comment]
https://github.com/TooTallNate/node-pac-resolver/pull/24 should fix this. @TooTallNate is this mergeable for you?

**Comment by Morl99** [comment]
Any chances to get a fix for this on the road? I am kindly asking if there is anything we can still do to help.

**Comment by slaingod** [comment]
I had a PAC that had multiple calls to myIpAddress() in it and ran into issues with the result not being cached. PAC was not ours, but the client enterprise's so not something I could get their network team to change just because pac-resolver wasn't performant. I was able to work around by overriding the myIpAddress() in the javascript, basically appending a myIpAddress method to the PAC javascript that used cached values. 

I just needed caching to work, so this was sufficient for me, but someone else may find this helpful for overriding the way this module determines the result of myIpAddress() or some other PAC method. The pac-resolver doesn't provide for any caching obviously for the results of running a url through the resolver, but that is solvable externally, the need to cache myIpAddress or perhaps dnsResolve might require overriding them like this internally.

```
var myIpAddress = null;
// this is expensive, 25ms
pac.sandbox.myIpAddress().then((result) => {
    log(`Caching ${result} for myIpAddress()`);
    myIpAddress = result;
});

var ip_monkey_patch = `
function myIpAddress() {
    return override_myIpAddress();
}
`;

function override_myIpAddress() {
    return myIpAddress;
}
...
pac(pac_str + ip_monkey_patch, {sandbox: { override_myIpAddress: override_myIpAddress}}
```

**Comment by GerbenRampaart** [comment]
For anyone finding this helpful, I've encountered this as well. The dns lookup in this package happens using the google dns (8.8.8.8). Which, since I'm using this module on a corporate network, I'm never interested in the public ip, but only in the workstation ip. Therefore, the fallback (ip.address) is what I want.

You can fix this in a natural way because the module supports fixing this, so I would not even call it monkey-patching, because it's not a hack.

``typescript
  const options: PacResolverOptions = {
    displayErrors: true,
    output: 'async',
    sandbox: {
      // The pac resolver uses google (8.8.8.8) to resolve the public ip.
      // However for ADP we just need the local ip.
      // The DNS request to google also takes longer ans sometimes times out.
      myIpAddress: (): string => {
        return ip.address();
      },
    },
  };

  const parsedPac = pac('the string containing the pac file', options);

**Comment by GerbenRampaart** [comment]
Since you can fix this within the parameters of the module plus it's not the responsibility of this module to fix firewall route 53 issues, I would just close this @TooTallNate

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
